# Import des prompts et configurations
from .prompts import (
    REQUIREMENTS_ANALYZER_PROMPT,
    ARCHITECTURE_DESIGNER_PROMPT,
    DATABASE_DESIGNER_PROMPT,
    API_DESIGNER_PROMPT,
    CODE_GENERATOR_PROMPT,
    TEST_GENERATOR_PROMPT,
    CODE_REVIEWER_PROMPT,
    FILE_SIGNATURE_EXTRACTOR_PROMPT,
    CROSS_FILE_REVIEWER_PROMPT,
    APP_FIXER_PROMPT,
    PROJECT_FILES_GENERATOR_PROMPT,
    CSS_DESIGNER_PROMPT,
    REFORMULATION_PROMPT,
    MULTI_FILE_GENERATOR_PROMPT,
    BACKEND_DEVELOPER_PROMPT
)

# Import des constantes de configuration
from .config import (
    API_MODEL,
    API_TEMPERATURE,
    MAX_TOKENS_DEFAULT,
    MAX_TOKENS_LARGE,
    MAX_TOKENS_HUGE
)

# Import des constantes depuis constants.py
from .constants import (
    USE_OPENROUTER,
    OPENROUTER_BASE_URL,
    OPENROUTER_MODEL,
    AGENT_TEAM_ENABLED,
    AGENT_TEAM_WAIT_TIME,
    TEMPERATURES
)
